name: Review PR
on: [pull_request]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v2

      - name: 🏗 Setup Node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🧪 Test
        run: yarn test
